#!/bin/bash

# nasm -f elf first_lab.asm
# gcc -m32 -o runner first_lab.o
# ./runner

string="$1"

# echo $string
# echo ${string/asm/o}
# echo ${string/.asm/}

nasm -f elf32 $string
gcc -m32 -o  ${string/.asm/} ${string/asm/o} -fPIC
./${string/.asm/}