package gui;

import functions.exceptions.InappropriateFunctionPointException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Locale;
import java.util.ResourceBundle;

@SuppressWarnings({"BoundFieldAssignment", "Duplicates"})
public class MainWindow extends JFrame {
    private final String PATH_TO_RESOURCES = "gui/resources/languagePackage";
    JRadioButtonMenuItem russianButton;
    JRadioButtonMenuItem englishButton;
    private JPanel mainPanel;
    private JButton deletePointButton;
    private JTextField xValueField;
    private JTextField yValueField;
    private JTable pointsViewTable;
    private JButton addPointButton;
    private JLabel xPointLabel;
    private JLabel yPointLabel;
    private JScrollPane tableScrollPane;
    private JMenuBar menuBar;
    private JMenu fileMenu;
    private JMenuItem createMenuItem;
    private JMenuItem createArrayTypeItem;
    private JMenuItem createLinkedListTypeItem;
    private JMenuItem createCustomTypeItem;
    private JMenuItem openMenuItem;
    private JMenuItem saveMenuItem;
    private JMenuItem saveAsMenuItem;
    private JMenuItem exitMenuItem;
    private JMenu tabulateMenu;
    private JMenuItem tabulateMenuItem;
    private JMenu optionsMenu;
    private JMenuItem changeThemeMenuItem;
    private JMenuItem changeLangMenuItem;
    private JMenu helpMenu;
    private JMenuItem checkForUpdatesItem;
    private JMenuItem aboutMenuItem;
    private TabulatedFunctionHandler functionHandler;
    private Locale russianLocale;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public MainWindow() {

        russianLocale = new Locale.Builder().setLanguage("ru").setRegion("RU").build();

        pointsViewTable.registerKeyboardAction(e -> onDelete(), KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0),
                JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

        //TODO не работает
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowLostFocus(WindowEvent e) {
                saveCurrentCondition();
            }
        });


        setMinimumSize(new Dimension(400, 450));
        setTitle("PriseTheFunctionAPP");
        setIconImage((new ImageIcon("./src/main/gui/resources/icon.png")).getImage());
        setContentPane(mainPanel);
        setResizable(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setupButtons();
        setupFields();
        setupTable();
        menuInit();
        setJMenuBar(menuBar);
        updateWindow();
        pack();
        setVisible(true);
    }

    public static void main(String[] args) {
        MainWindow window = new MainWindow();
    }

    private void menuInit() {
        menuBar = new JMenuBar();
        fileMenuInit(menuBar);
        tabulateMenuInit(menuBar);
        optionsMenuInit(menuBar);
        helpMenuInit(menuBar);
    }

    private void optionsMenuInit(JMenuBar parent) {
        optionsMenu = new JMenu();
        optionsMenu.setMnemonic('o');

        changeThemeMenuItem = new JMenuItem();
        changeThemeMenuItem.addActionListener(actionEvent -> new ChangeThemeFrame(this));

        changeLangMenuItem = new JMenu();

        ButtonGroup langs = new ButtonGroup();
        russianButton = new JRadioButtonMenuItem(setUpText("menu.options.changelang.russian"), false);
        russianButton.addActionListener(actionEvent -> {
            Locale.setDefault(russianLocale);
            ResourceBundle.clearCache();
            updateWindow();
            repaint();
        });
        englishButton = new JRadioButtonMenuItem(setUpText("menu.options.changelang.english"), true);
        englishButton.addActionListener(actionEvent -> {
            Locale.setDefault(Locale.US);
            ResourceBundle.clearCache();
            updateWindow();
            repaint();
        });
        langs.add(russianButton);
        langs.add(englishButton);
        changeLangMenuItem.add(russianButton);
        changeLangMenuItem.add(englishButton);

        optionsMenu.add(changeThemeMenuItem);
        optionsMenu.add(changeLangMenuItem);
        parent.add(optionsMenu);
    }

    private void helpMenuInit(JMenuBar parent) {
        helpMenu = new JMenu();
        helpMenu.setMnemonic('h');

        checkForUpdatesItem = new JMenuItem();
        checkForUpdatesItem.setEnabled(false);
        checkForUpdatesItem.addActionListener(actionEvent -> {
            //TODO
        });

        aboutMenuItem = new JMenuItem();
        aboutMenuItem.addActionListener(actionEvent -> {
            try {
                Desktop.getDesktop().open(new File("./aboutpage/index.html"));
            } catch (IOException e) {
                e.printStackTrace();
            }
        });

        helpMenu.add(checkForUpdatesItem);
        helpMenu.add(aboutMenuItem);
        parent.add(helpMenu);
    }

    private void tabulateMenuInit(JMenuBar parent) {
        tabulateMenu = new JMenu();
        tabulateMenu.setMnemonic('t');

        tabulateMenuItem = new JMenuItem();
        tabulateMenuItem.setAccelerator(KeyStroke.getKeyStroke("ctrl T"));
        tabulateMenuItem.addActionListener(actionEvent -> {
            FunctionParamsDialog dialog = new FunctionParamsDialog();
            Object[] params = dialog.showDialog();
            if ((int) params[0] == 1) {
                try {
                    functionHandler.tabulateFunction((double) params[1], (double) params[2], (int) params[3]);
                } catch (InappropriateFunctionPointException e) {
                    e.printStackTrace();
                }
            }
            updateTable();
        });

        tabulateMenu.add(tabulateMenuItem);
        parent.add(tabulateMenu);
    }

    private void fileMenuInit(JMenuBar parent) {
        fileMenu = new JMenu();
        fileMenu.setMnemonic('f');

        createMenuItem = new JMenuItem();
        createMenuItem.setAccelerator(KeyStroke.getKeyStroke("ctrl N"));
        createMenuItem.addActionListener(actionEvent -> {
            CreateCustomFunction function = new CreateCustomFunction();
            functionHandler = function.showDialog();
            if (functionHandler != null) {
                updateTable();
            }
        });

        openMenuItem = new JMenuItem();
        openMenuItem.setAccelerator(KeyStroke.getKeyStroke("ctrl O"));
        openMenuItem.addActionListener(actionEvent -> {
            saveCurrentCondition();
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File("./saves"));
            fileChooser.showOpenDialog(this);
            fileChooser.setMultiSelectionEnabled(false);
            File file = fileChooser.getSelectedFile();
            if (file != null) {
                try {
                    functionHandler = new TabulatedFunctionHandler(file.getName());
                    updateTable();
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });

        saveMenuItem = new JMenuItem();
        saveMenuItem.setAccelerator(KeyStroke.getKeyStroke("ctrl S"));
        saveMenuItem.addActionListener(actionEvent -> {
            saveCurrentCondition();
        });

        saveAsMenuItem = new JMenuItem();
        saveAsMenuItem.addActionListener(actionEvent -> {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File("./saves"));
            fileChooser.showSaveDialog(this);
            try {
                functionHandler.saveFunctionAs(fileChooser.getName());
            } catch (IOException ex) {
                String msg = "Can't save current function";
                JOptionPane.showMessageDialog(this, ex.getMessage() + msg);
            }
        });

        exitMenuItem = new JMenuItem();
        exitMenuItem.setAccelerator(KeyStroke.getKeyStroke("ctrl Q"));
        exitMenuItem.addActionListener(actionEvent -> {
            saveCurrentCondition();
            this.dispose();
            System.exit(1);
        });

        fileMenu.add(createMenuItem);
        fileMenu.add(openMenuItem);
        fileMenu.add(saveMenuItem);
        fileMenu.add(saveAsMenuItem);
        fileMenu.add(exitMenuItem);
        parent.add(fileMenu);
    }

    private void setupFields() {
        xValueField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                checkForNoneDigits(e, xValueField);
            }
        });

        yValueField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                checkForNoneDigits(e, yValueField);
            }
        });
    }

    private void onAdd() {
        if (xValueField.getText().isEmpty() || yValueField.getText().isEmpty()) {
            //Nothing
            return;
        }
        double x = Double.parseDouble(xValueField.getText());
        double y = Double.parseDouble(yValueField.getText());
        System.out.println(x + "; " + y);
        ((DefaultTableModel) pointsViewTable.getModel()).addRow(new Object[]{x, y});
    }

    private void onDelete() {
        int[] indexes = pointsViewTable.getSelectedRows();
        if (indexes.length == 0) {
            return;
        }
        for (int i = indexes.length - 1; i >= 0; --i) {
            ((DefaultTableModel) pointsViewTable.getModel()).removeRow(indexes[i]);
        }
    }

    private void checkForNoneDigits(KeyEvent e, JTextField field) {
        char ch = e.getKeyChar();
        if (ch == '.' && field.getText().chars().filter(dots -> dots == '.').count() != 0) {
            e.consume();
        } else if (!Character.isDigit(ch) && ch != '.') {
            e.consume();
        }
    }

    private void setupButtons() {
        addPointButton.addActionListener(e -> onAdd());
        deletePointButton.addActionListener(e -> onDelete());
    }

    private void setupTable() {
        FunctionTableModel table = new FunctionTableModel(this);
        pointsViewTable.setModel(table);
    }

    private void updateTable() {
        FunctionTableModel model = (FunctionTableModel) pointsViewTable.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        int count = functionHandler.getPointsCount();
        for (int i = 0; i < count; ++i) {
            double x = functionHandler.getPointX(i);
            double y = functionHandler.getPointY(i);
            model.addRow(new Object[]{x, y});
        }
    }

    private boolean isEmptyTable() {
        return pointsViewTable.getRowCount() == 0;
    }

    private void saveCurrentCondition() {
        if (!isEmptyTable()) {
            try {
                if (functionHandler.isFilenameAssigned()) {
                    functionHandler.saveFunction();
                } else {
                    String msg = "Enter a filename";
                    String answer = JOptionPane.showInputDialog(this,
                            msg, "Warning!", JOptionPane.WARNING_MESSAGE);
                    functionHandler.saveFunctionAs(answer);
                }
            } catch (IOException ex) {
                JOptionPane.showInputDialog(this, ex.getMessage(), "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    private String setUpText(String key) {
        return ResourceBundle.getBundle(PATH_TO_RESOURCES).getString(key);
    }

    private void updateWindow() {
        fileMenu.setText(setUpText("menu.file"));
        createMenuItem.setText(setUpText("menu.file.new"));
        openMenuItem.setText(setUpText("menu.file.open"));
        saveMenuItem.setText(setUpText("menu.file.save"));
        saveAsMenuItem.setText(setUpText("menu.file.saveas"));
        exitMenuItem.setText(setUpText("menu.file.exit"));

        tabulateMenuItem.setText(setUpText("menu.tabulate.changeparams"));
        tabulateMenu.setText(setUpText("menu.tabulate"));

        optionsMenu.setText(setUpText("menu.options"));
        changeLangMenuItem.setText(setUpText("menu.options.changelang"));
        changeThemeMenuItem.setText(setUpText("menu.options.changetheme"));

        helpMenu.setText(setUpText("menu.help"));
        aboutMenuItem.setText(setUpText("menu.help.about"));
        checkForUpdatesItem.setText(setUpText("menu.help.checkupdate"));

        russianButton.setText(setUpText("menu.options.changelang.russian"));
        englishButton.setText(setUpText("menu.options.changelang.english"));

        xPointLabel.setText(setUpText("new.point.x"));
        yPointLabel.setText(setUpText("new.point.y"));
        addPointButton.setText(setUpText("add.point.btn"));
        deletePointButton.setText(setUpText("delete.point.btn"));
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setMaximumSize(new Dimension(1920, 1080));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        deletePointButton = new JButton();
        this.$$$loadButtonText$$$(deletePointButton, ResourceBundle.getBundle("gui/resources/languagePackage").getString("delete.point.btn"));
        panel1.add(deletePointButton, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(120, -1), null, 0, false));
        xPointLabel = new JLabel();
        this.$$$loadLabelText$$$(xPointLabel, ResourceBundle.getBundle("gui/resources/languagePackage").getString("new.point.x"));
        panel1.add(xPointLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        yPointLabel = new JLabel();
        this.$$$loadLabelText$$$(yPointLabel, ResourceBundle.getBundle("gui/resources/languagePackage").getString("new.point.y"));
        panel1.add(yPointLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        xValueField = new JTextField();
        xValueField.setHorizontalAlignment(4);
        xValueField.setText("");
        panel1.add(xValueField, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(120, -1), null, 0, false));
        yValueField = new JTextField();
        yValueField.setHorizontalAlignment(4);
        panel1.add(yValueField, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(120, -1), null, 0, false));
        addPointButton = new JButton();
        this.$$$loadButtonText$$$(addPointButton, ResourceBundle.getBundle("gui/resources/languagePackage").getString("add.point.btn"));
        panel1.add(addPointButton, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(120, -1), null, 0, false));
        tableScrollPane = new JScrollPane();
        mainPanel.add(tableScrollPane, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        pointsViewTable = new JTable();
        pointsViewTable.setUpdateSelectionOnSort(true);
        tableScrollPane.setViewportView(pointsViewTable);
        xPointLabel.setLabelFor(xValueField);
        yPointLabel.setLabelFor(yValueField);
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadLabelText$$$(JLabel component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setDisplayedMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadButtonText$$$(AbstractButton component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
